### ISSUE TITLE
simple-drawer Close button

### ISSUE THREAD

**Issue by JackWillDavis** [buttercupstraining/lrnwebcomponents#1]
Testing a complete fix/build/submit process into the elmsln/lrnwebcomponents repo.

The lrnsys-drawer component needs tweaking. The close button should:

* Have editable styling
* Have text aligned with icon
* Have cursor:pointer

![image](https://user-images.githubusercontent.com/2301874/105190480-f1019200-5b2d-11eb-9cec-bc0acc2edd68.png)

**Comment by rickhumphries** [comment]
For the 'apps' menu, need to use `filter` to target the svg icon. Something like...

```css
svg {
filter: var(--lrnsys-drawer-svg-icon-color, invert(27%) sepia(51%) saturate(2878%) hue-rotate(346deg) brightness(104%) contrast(97%));
}

**Comment by rickhumphries** [comment]
This looks fixed now :)
